name: docker_build_and_push.yml
on:
  workflow_run:
    workflows: ["Run code quality tests"]
    types:
      - completed

env:
  # image_tag: {branch}_{full_sha}_{run_id}
  IMAGE_TAG: "${{ github.head_ref || github.ref_name }}_${{ github.sha }}_${{github.run_id}}"
  SERVER_PORT: 8989
  SERVER_TIMEOUT_READ: 3s
  SERVER_TIMEOUT_WRITE: 5s
  SERVER_TIMEOUT_IDLE: 5s
  SERVER_DEBUG: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go mod tidy
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker compose build
      - run: docker compose push

